### PR TITLE
Bump Kover version

### PR DESCRIPTION
**Pull request by fb64**
#594

### CODE REVIEW

**Comment by koperagen** [comment]
Hi! Thank you for the PR :) Please fix :ktlintKotlinScriptCheck

**Comment by fb64** [comment]
> Hi! Thank you for the PR :) Please fix :ktlintKotlinScriptCheck

Fixed,  is `:ktlintKotlinScriptCheck` supposed to run during a `clean build` because I didn't get any error...

**Comment by koperagen** [comment]
> > Hi! Thank you for the PR :) Please fix :ktlintKotlinScriptCheck
> 
> Fixed, is `:ktlintKotlinScriptCheck` supposed to run during a `clean build` because I didn't get any error...

No, it should run without clean build. We need to investigate this problem, thanks for letting me know

**Comment by fb64** [comment]
I mean, I didn't get any error with `clean build` but I got it with `:ktlintKotlinScriptCheck` single task... Maybe this task should be included in `build` task or git pre-commit to let developers know that there is an issue before committing.

**Comment by koperagen** [comment]
Ah, ok, i misunderstood. But i thought build already depends check which in turn depends on ktlintKotlinScriptCheck.. need to verify. I noticed that sometimes linkCheck tasks don't print errors even when they run

**Pull request merged**
