### PR TITLE
Fix #640: Jupyter integration conflicts with variable type converters from other integrations

### LINKED ISSUE #640: Jupyter integration conflicts with variable type converters from other integrations.
# Steps to reproduce
Cell 1:
```kotlin
notebook.fieldsHandlersProcessor.register(
    // replacing all byte array variables with lists
    extension = FieldHandlerFactory.createUpdateHandler<ByteArray>(TypeDetection.COMPILE_TIME) { _, prop ->
        execute("${prop.name}.toList()").name
    },
)
```

Cell 2:
```kotlin
%use dataframe
val x = ByteArray(1)
```
Cell 3:
```kotlin
x.javaClass
```
# Expected output:
`class java.util.Collections$SingletonList` (that means that the byte array was transformed into a list as we asked it to in the fieldsHandlersProcessor).
You can also get this output by commenting out `%use dataframe`, restarting the kernel and rerunning the notebook.
# Actual output:
`class [B` (the byte array stayed byte array).

### PR DESCRIPTION
**Pull request by ark-1**
Fixes #640

### CODE REVIEW

**Comment by koperagen** [comment]
It was done on purpose, see the test. I think this should be fixed on kernel side, if possible. It's not obvious why when our function returns null no other converters are called
https://github.com/Kotlin/dataframe/blob/0f49f720569162dc12e23b40e25efc0e3f5797a3/core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/jupyter/CodeGenerationTests.kt#L16

**Comment by ark-1** [comment]
I will discuss changing this behavior on the kernel side. Still, your case is already supported by a different API, so I suggest changing it nevertheless.

**Comment by Jolanrensen** [comment]
Yes, we need to make sure this https://github.com/Kotlin/dataframe/pull/401 still works

**Comment by Jolanrensen** [comment]
All tests pass, also the ones introduced by https://github.com/Kotlin/dataframe/pull/401, so should be good to go :)

**Review by Jolanrensen — APPROVED** [review]

**Comment by ark-1** [comment]
The problem with the proposed code that it didn't guarantee the ordering of checks and conversions.
I have rewritten the code to use full FieldHandler API, that has a separate `accepts` method.

**Pull request merged**
