### PR TITLE
migrate Titanic.ipynb to Kandy

### PR DESCRIPTION
**Pull request by koperagen**
https://github.com/Kotlin/dataframe/issues/437
I realized that there's no CorrPlot a bit too late, but found that corr + gather can prepare data for plotting very well too, yielding almost the same results. Also adjusted the look.

### CODE REVIEW

**Comment by zaleslaw** [comment]
I have an idea to post code changes here, if they are not so large, because Github doesn't support good diffs for Notebooks

**Comment by Jolanrensen** [comment]
Please run it with the latest master so that the tables render correctly for github :)

**Review by Jolanrensen — CHANGES_REQUESTED** [review]
I'll review like `cell:line: comment` :)

 - 15:6: Probably replace with `JetBrainsColors.darkGrey` right?
 - 19:1: Very long line, maybe split it across multiple 
 - 21:3: Also long, but better than the last one
 - 31:: Hmm, the color of the small circles is very hard to see, could these be scaled up?
 
Like I said in the previous comment, please run the notebook from the master branch published to mavenLocal such that the tables render on GH :)
Other than that, very nice! Kandy is so much easier to read than Let's Plot haha

**Comment by Jolanrensen** [comment]
I'll merge this for now and check it for 0.13.1-RC1

**Pull request merged**
