### PR TITLE
google analytics script

### PR DESCRIPTION
**Pull request by azhebel**
also:
- meta name="google-site-verification"
- iframe resize function

not sure if they are necessary though

### CODE REVIEW

**Comment by koperagen** [comment]
Hi! We're using a bit outdated custom writerside build, 2023.1.4. This tag doesn't seem to work there. 
image
So let's keep analytics-head-script-file. These are needed too, indeed
```
meta name="google-site-verification"
iframe resize function
```

**Comment by azhebel** [comment]
@koperagen sure, you can keep the old tag `<analytics-head-script-file>` and even the old script file if you want, just make sure the actual analytics script is the one I added here, not the UA one you had previously

Do you want me to modify this MR or will you add the necessary changes manually?

**Comment by koperagen** [comment]
Modify the MR please :)

**Comment by azhebel** [comment]
@koperagen I kept everything else except the actual script. Let's see if this helps.

**Comment by koperagen** [comment]
Thank you! I'll deploy docs now

**Pull request merged**
